tupla_times = ('Palmeiras', 'Fluminense', 'Flamengo', 'Corinthians', 'Internacilnal', 'Athletico-PR', 'Atletico-Mg', 'Santos', 'América-MG', 'Bragantino', 'Goiás', 'São Paulo', 'Fortaleza', 'Botafogo', 'Ceará SC', 'Cuiabá', 'Avaí', 'Coritiba', 'Atlético-GO', 'Juventude')
sp = tupla_times.index('São Paulo')
print('=+=' * 100)
print(f'Lista de times do Brasileirão: {tupla_times}')
print('=+=' * 100)
print(f'Os cinco primeiro são: {tupla_times[:5]}')
print('=+=' * 100)
print(f'Os quatro ultimos são: {tupla_times[-4:21]}')
print('=+=' * 100)
print(f'Times em ordem alfebética: {sorted(tupla_times)}')
print('=+=' * 100)
print(f'São paulo esta em: {sp} lugar')
print('=+=' * 100)